use std::fs;
use std::path::Path;

use anyhow::Result;

const TEMPLATE: &str = r#"// __NAME__ — generated by verun init

state __NAME__ {
    value: int

    invariant non_negative {
        value >= 0
    }

    init {
        value = 0
    }

    transition increment(amount: int) {
        where {
            amount > 0
        }
        value += amount
        ensure {
            value == old(value) + amount
        }
    }
}
"#;

pub fn execute(name: &str, output: Option<&str>) -> Result<()> {
    let content = TEMPLATE.replace("__NAME__", name);

    let filename = output
        .map(String::from)
        .unwrap_or_else(|| format!("{}.verun", name.to_lowercase()));

    if Path::new(&filename).exists() {
        anyhow::bail!("file '{}' already exists", filename);
    }

    fs::write(&filename, content)?;
    eprintln!("Created {}", filename);

    Ok(())
}
